# Generated by Django 4.1.3 on 2022-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('migratory', models.BooleanField()),
                ('range', models.CharField(max_length=100)),
            ],
        ),
    ]
