# Generated by Django 4.1.3 on 2022-11-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_seed_alter_sighting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='seeds',
            field=models.ManyToManyField(to='main_app.seed'),
        ),
    ]
